_base_: 'lung_coronavirus_test.yml'

model:
  type: UNet
  in_channels: 1
  num_classes: 3

comment: "Unet full, no ds4, late shortcut with bias, first encode norm"
vdl_hyper_param:
  dropout: 0.2
  norm: "instance norm"