_base_: 'lung_coronavirus.yml'

# 16g, 37 iter/epoch
batch_size: 4
iters: 3000

# 32g, 
batch_size: 8
iters: 3000

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 15000
  learning_rate: 0.01
  end_lr: 0.0001
  power: 0.9

model:
  type: UNet
  in_channels: 1
  num_classes: 3

comment: "Unet full, baseline, 128"
vdl_hyper_param:
  dropout: 0.2
  norm: "instance norm"